// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-Jv_wdyCfBmiwN6wNq6cuFIPpCOObkY',
    appId: '1:969081971153:web:02584bd0c3ec665f4c00f0',
    messagingSenderId: '969081971153',
    projectId: 'lessify-ccc12',
    authDomain: 'lessify-ccc12.firebaseapp.com',
    storageBucket: 'lessify-ccc12.firebasestorage.app',
    measurementId: 'G-XSRMQE5BGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCliGAbU4x1D6NrXRrm_IiPQfOrbiFOmr8',
    appId: '1:969081971153:android:09f4666b44c50a414c00f0',
    messagingSenderId: '969081971153',
    projectId: 'lessify-ccc12',
    storageBucket: 'lessify-ccc12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhezjrDTcDF8_rX7iyk3MM562EjZNAzbs',
    appId: '1:969081971153:ios:dfc66eee9d1983c14c00f0',
    messagingSenderId: '969081971153',
    projectId: 'lessify-ccc12',
    storageBucket: 'lessify-ccc12.firebasestorage.app',
    iosBundleId: 'com.getlessify.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhezjrDTcDF8_rX7iyk3MM562EjZNAzbs',
    appId: '1:969081971153:ios:6b39876649e4ce764c00f0',
    messagingSenderId: '969081971153',
    projectId: 'lessify-ccc12',
    storageBucket: 'lessify-ccc12.firebasestorage.app',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-Jv_wdyCfBmiwN6wNq6cuFIPpCOObkY',
    appId: '1:969081971153:web:428486acc7dbc5254c00f0',
    messagingSenderId: '969081971153',
    projectId: 'lessify-ccc12',
    authDomain: 'lessify-ccc12.firebaseapp.com',
    storageBucket: 'lessify-ccc12.firebasestorage.app',
    measurementId: 'G-DKLM4NS0V6',
  );
}
